package command

import (
	"context"
	"fmt"
	"modfit/internal/platform"
	"os"

	"github.com/BurntSushi/toml"
)

type ConfigGenerateAction struct{}

func (cmd ConfigGenerateAction) Name() string {
	return "generate"
}

func (cmd ConfigGenerateAction) ShortDescr() string {
	return "Generate a modfit config file"
}

func (cmd ConfigGenerateAction) UsageStr() string {
	return "PLACEHOLDER usage for [config generate]"
}

type ConfigGenerateArgs struct {
	BaseArgs
}

func (cmd ConfigGenerateAction) Run(ctx context.Context, args []string) {
	parsedArgs := new(ConfigGenerateArgs)
	baseFlags := InitBaseFlags(&parsedArgs.BaseArgs)
	baseFlags.Parse(args)

	// Error usually means that we didn't find the file. If something will prevent us writing the
	// file, we'll encounter that later anyway.
	configPath, foundFile, _  := platform.GetConfigPath(parsedArgs.ConfigPath)
	if foundFile {
		platform.FailOut(fmt.Sprintf("Resolved config file path already exists: %s", configPath))
	}

	configFile, err := os.Create(configPath)
	defer configFile.Close()
	if err != nil {
		platform.FailOut(fmt.Sprintf(
			"Could not open file for writing: %s\n%s",
			configPath,
			err.Error(),
		))
	}

	_, err = configFile.WriteString("# this file was generated by modfit\n")
	if err != nil {
		platform.FailOut(err.Error())
	}

	tomlEncoder := toml.NewEncoder(configFile)
	err = tomlEncoder.Encode(platform.DefaultConfig())
	if err != nil {
		platform.FailOut(fmt.Sprintf(
			"Failed to write default config to %s, but the file was created successfully. You " +
				"may wish to delete this file.\n%s",
			configPath,
			err.Error(),
		))
	}
}
